name: Bash Manual # You can add your own name for the pipeline here

# Trigger when committing to main branch
on:
  workflow_dispatch: # Allow manual triggering of the workflow
    inputs:
      target:
        type: choice
        description: Select target environment
        default: dev
        options: 
        - dev
        - stage
        - live

jobs:
  # Get changes from cloud
  cloud-sync:
    name: "Umbraco Cloud Sync"
    uses: ./.github/workflows/cloud-sync.yml
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
    with:
      targetEnvironmentAlias: ${{ github.event.inputs.target }}

  # Pack and upload the deployment Artifact
  cloud-artifact:
    name: "Prepare and Upload Artifact"
    uses: ./.github/workflows/cloud-artifact.yml
    needs: cloud-sync
    with:
      newSha: ${{ needs.cloud-sync.outputs.newSha }}
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}

  # Deploy to Umbraco Cloud
  # ####
  # you can edit the variables noBuildAndRestore, skipVersionCheck and allowAnyTarget
  # use booleans but as strings
  cloud-deployment:
    name: "Deploy to Cloud"
    needs: cloud-artifact
    uses: ./.github/workflows/cloud-deployment.yml
    with:
      artifactId: ${{ needs.cloud-artifact.outputs.artifactId }}
      targetEnvironmentAlias: ${{ github.event.inputs.target }}
      noBuildAndRestore: "true"
      skipVersionCheck: "true"
      allowAnyTarget: "true"
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
